# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43d0a28287ad93a610af4aa50dabb1e8d51a7830c3eabec7bf1b27f355aa330320ee21fa321b204573f8608ca9d001e8b4f63c7da6c0ee1a2deae0c3841a89ef

test:
  secret_key_base: fcf2de61f49afa8a2e105a56a2e7fefa103685af9eeabc3df8621ae2c8ece3620decaea796ce72f8b98dc05d953bc60de2b3213e440f0db5170144ab68bda3dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
